import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';
import React from 'react';
import Navigation from '@/Components/Navigation/Navigation';
import Footer from '@/Components/Footer/Footer';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default ({ children }: { children: React.ReactNode }) => (
	<html lang='en'>
		<body className={`${openSans.className} bg-white-100`}>
			<Navigation />
			{children}
			<Footer />
		</body>
	</html>
);
